//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODAF.SilverlightApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainPageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainPageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODAF.SilverlightApp.Resources.MainPageResource", typeof(MainPageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add a Landmark.
        /// </summary>
        public static string AddALandmark {
            get {
                return ResourceManager.GetString("AddALandmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fork me on GitHub.
        /// </summary>
        public static string ForkMeOnGitHub {
            get {
                return ResourceManager.GetString("ForkMeOnGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide all Map Attributes.
        /// </summary>
        public static string HideallMapAttributes {
            get {
                return ResourceManager.GetString("HideallMapAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosted in the cloud with MS-Azure.
        /// </summary>
        public static string HostedInAzure {
            get {
                return ResourceManager.GetString("HostedInAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANDMARKS.
        /// </summary>
        public static string Landmarks {
            get {
                return ResourceManager.GetString("Landmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ODAF.SilverlightApp;component/Images/opendata_en.png.
        /// </summary>
        public static string LogoPath {
            get {
                return ResourceManager.GetString("LogoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP ATTRIBUTES.
        /// </summary>
        public static string MapAttributes {
            get {
                return ResourceManager.GetString("MapAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby Tweets.
        /// </summary>
        public static string NearbyTweets {
            get {
                return ResourceManager.GetString("NearbyTweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/openlab/Openturf.
        /// </summary>
        public static string OdafLink {
            get {
                return ResourceManager.GetString("OdafLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://vanguide.cloudapp.net.
        /// </summary>
        public static string OgdifranceLink {
            get {
                return ResourceManager.GetString("OgdifranceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGION.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and the ODAF OpenTurf SDK.
        /// </summary>
        public static string SdkOdaf {
            get {
                return ResourceManager.GetString("SdkOdaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Landmarks.
        /// </summary>
        public static string SharedLandmarks {
            get {
                return ResourceManager.GetString("SharedLandmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIAL LANDMARKS.
        /// </summary>
        public static string SocialLandmarks {
            get {
                return ResourceManager.GetString("SocialLandmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the data catalog of Vancouver.
        /// </summary>
        public static string UseCatalog {
            get {
                return ResourceManager.GetString("UseCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR LANDMARKS.
        /// </summary>
        public static string YourLandmarks {
            get {
                return ResourceManager.GetString("YourLandmarks", resourceCulture);
            }
        }
    }
}
