//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODAF.Website.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODAF.Website.Resources.Views.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Landmark.
        /// </summary>
        public static string AddLandmark {
            get {
                return ResourceManager.GetString("AddLandmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        public static string AppBlockTitle {
            get {
                return ResourceManager.GetString("AppBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect with Twitter.
        /// </summary>
        public static string ConnectWithTwitter {
            get {
                return ResourceManager.GetString("ConnectWithTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string DataBlockTitle {
            get {
                return ResourceManager.GetString("DataBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag the pin to place your landmark.
        /// </summary>
        public static string DragPin {
            get {
                return ResourceManager.GetString("DragPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide all Map Attributes.
        /// </summary>
        public static string HideAttributes {
            get {
                return ResourceManager.GetString("HideAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANDMARKS.
        /// </summary>
        public static string Landmarks {
            get {
                return ResourceManager.GetString("Landmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP ATTRIBUTES.
        /// </summary>
        public static string MapAttributes {
            get {
                return ResourceManager.GetString("MapAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing mandatory field(s).
        /// </summary>
        public static string MissingLandmarkField {
            get {
                return ResourceManager.GetString("MissingLandmarkField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby Tweets.
        /// </summary>
        public static string NearbyTweets {
            get {
                return ResourceManager.GetString("NearbyTweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGION.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Landmarks.
        /// </summary>
        public static string SharedLandmarks {
            get {
                return ResourceManager.GetString("SharedLandmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIAL LANDMARKS.
        /// </summary>
        public static string SocialLandmarks {
            get {
                return ResourceManager.GetString("SocialLandmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a comment.
        /// </summary>
        public static string StringAddComment {
            get {
                return ResourceManager.GetString("StringAddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on a star to add your rating.
        /// </summary>
        public static string StringAddRating {
            get {
                return ResourceManager.GetString("StringAddRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a tag.
        /// </summary>
        public static string StringAddTag {
            get {
                return ResourceManager.GetString("StringAddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already rated this landmark.
        /// </summary>
        public static string StringAlreadyRated {
            get {
                return ResourceManager.GetString("StringAlreadyRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comments.
        /// </summary>
        public static string StringComments {
            get {
                return ResourceManager.GetString("StringComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string StringDelete {
            get {
                return ResourceManager.GetString("StringDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info.
        /// </summary>
        public static string StringInfo {
            get {
                return ResourceManager.GetString("StringInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have rated this landmark.
        /// </summary>
        public static string StringRated {
            get {
                return ResourceManager.GetString("StringRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your rating was not saved, please try again.
        /// </summary>
        public static string StringRateError {
            get {
                return ResourceManager.GetString("StringRateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ratings.
        /// </summary>
        public static string StringRating {
            get {
                return ResourceManager.GetString("StringRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to sign in to rate this landmark.
        /// </summary>
        public static string StringSignInToRate {
            get {
                return ResourceManager.GetString("StringSignInToRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to star.
        /// </summary>
        public static string StringStar {
            get {
                return ResourceManager.GetString("StringStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tags.
        /// </summary>
        public static string StringTag {
            get {
                return ResourceManager.GetString("StringTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string SupportBlockTitle {
            get {
                return ResourceManager.GetString("SupportBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 letters or more.
        /// </summary>
        public static string TextTooltip {
            get {
                return ResourceManager.GetString("TextTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Landmarks.
        /// </summary>
        public static string YourLandmarks {
            get {
                return ResourceManager.GetString("YourLandmarks", resourceCulture);
            }
        }
    }
}
